[package]
name = "nyx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
sha-1 = "0.10.0"
hex = "0.4.3"
flate2 = "1.0.24"